title: Osiguraj.hr
repository: Filip-Gale/osiguraj.hr
permalink: /blog/:title/

collections:
  gradovi: # Ovo ostaje za tvoj stari projekt
    output: true
  tehnicki_pregled: # OVO JE NOVO
    output: true
    permalink: /tehnicki-pregled/:path/ 

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "gradovi" # Stari projekt
    values:
      layout: "post"
  - scope:
      path: ""
      type: "tehnicki_pregled" # NOVI PROJEKT
    values:
      layout: "tehnicki-layout" # Poseban layout za ovaj projekt
