title: Osiguraj.hr
repository: Filip-Gale/osiguraj.hr
permalink: /blog/:title/

collections:
  gradovi:
    output: true
  tehnicki_pregled:
    output: true
    permalink: /tehnicki-pregled/:path/
  registracija:
    output: true
    permalink: /registracija/:path/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "gradovi"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "tehnicki_pregled"
    values:
      layout: "tehnicki-layout"
  - scope:
      path: ""
      type: "registracija"
    values:
      layout: "registracija-layout"
